language: node_js  #设置语言

node_js: stable  #设置相应的版本

install:
  - npm install  #安装hexo及插件

script:
  - npm run dist  #生成

after_script:
  - cd ./dist
  - git init
  - git config user.name "Zeven"  #修改name
  - git config user.email "zevenfang@users.noreply.github.com"  #修改email
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:docs  #GH_TOKEN是在Travis中配置token的名称

branches:
  only:
    - master

env:
 global:
   - GH_REF: github.com/ZevenFang/react-redux-gallery.git
